<?php 
/**
 * Medvslav_News2 extension
 * 
 * NOTICE OF LICENSE
 * 
 * This source file is subject to the MIT License
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/mit-license.php
 * 
 * @category       Medvslav
 * @package        Medvslav_News2
 * @copyright      Copyright (c) 2016
 * @license        http://opensource.org/licenses/mit-license.php MIT License
 */
/**
 * Newscategory Article list template
 *
 * @category    Medvslav
 * @package     Medvslav_News2
 * @author      Medvslav
 */
?>
<?php $_articles = $this->getArticles(); ?>
<?php if ($_articles->getSize() > 0) :?>
<div class="article-title">
    <h2><?php echo Mage::helper('medvslav_news2')->__('Articles') ?></h2>
</div>
<div class="articles-list-container">
    <?php foreach ($_articles as $_article) : ?>
        <div class="article-list-item">
            <a href="<?php echo $_article->getArticleUrl()?>">
                <?php echo $_article->getTitle();?>
            </a><br />
        </div>
    <?php endforeach;?>
</div>
<?php endif;?>
