<?php 
/**
 * Medvslav_News2 extension
 * 
 * NOTICE OF LICENSE
 * 
 * This source file is subject to the MIT License
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/mit-license.php
 * 
 * @category       Medvslav
 * @package        Medvslav_News2
 * @copyright      Copyright (c) 2016
 * @license        http://opensource.org/licenses/mit-license.php MIT License
 */
/**
 * Article list template
 *
 * @category    Medvslav
 * @package     Medvslav_News2
 * @author      Medvslav
 */
?>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<?php $_articles = $this->getArticles(); ?>
<div class="page-title article-title">
    <?php if (Mage::helper('medvslav_news2/article')->isRssEnabled()) : ?>
        <a href="<?php echo Mage::helper('medvslav_news2/article')->getRssUrl();?>" class="link-rss"><?php echo Mage::helper('medvslav_news2')->__('Subscribe to RSS Feed')?></a>
    <?php endif;?>
    <h1><?php echo Mage::helper('medvslav_news2')->__('Articles') ?></h1>
</div>
<?php if ($_articles->getSize() > 0) :?>
    <?php echo $this->getPagerHtml(); ?>
    <div class="article-list-container">
    <?php foreach ($_articles as $_article) : ?>
        <div class="article-list-item">
            <a href="<?php echo $_article->getArticleUrl()?>">
                <?php echo $_article->getTitle();?>
            </a><br />
        </div>
    <?php endforeach;?>
    </div>
    <?php echo $this->getPagerHtml(); ?>
<?php else : ?>
    <?php echo Mage::helper('medvslav_news2')->__('There are no articles at this moment');?>
<?php endif;?>
