<?php
/**
 * Medvslav_News2 extension
 * 
 * NOTICE OF LICENSE
 * 
 * This source file is subject to the MIT License
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/mit-license.php
 * 
 * @category       Medvslav
 * @package        Medvslav_News2
 * @copyright      Copyright (c) 2016
 * @license        http://opensource.org/licenses/mit-license.php MIT License
 */
/**
 * Article view template
 *
 * @category    Medvslav
 * @package     Medvslav_News2
 * @author      Medvslav
 */
?>
<?php $_article = $this->getCurrentArticle();?>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<div class="page-title article-title">
    <h1><?php echo $_article->getTitle(); ?></h1>
</div>
<div class="article-view">
    <div class="article-title">
        <?php echo Mage::helper('medvslav_news2')->__('Title');?>:<?php echo $_article->getTitle();?>

    </div>
    <div class="article-description">
        <?php echo Mage::helper('medvslav_news2')->__('Description');?>:<?php echo $_article->getDescription();?>

    </div>
    <div class="article-content">
        <?php echo Mage::helper('medvslav_news2')->__('Content');?>:<?php echo $_article->getContent();?>

    </div>
    <div class="article-publication_date">
        <?php echo Mage::helper('medvslav_news2')->__("Publication_date");?>: <?php echo Mage::helper('core')->formatDate($_article->getPublicationDate(), 'full');?>

    </div>
    <div class="article-image">
        <?php if ($_article->getImage()) :?>
    <img src="<?php echo Mage::helper('medvslav_news2/article_image')->init($_article, 'image')->resize(75);?>" alt="<?php echo $this->escapeHtml($_article->getTitle());?>" />
<?php endif;?>

    </div>

</div>
