<?php 
/**
 * Medvslav_News2 extension
 * 
 * NOTICE OF LICENSE
 * 
 * This source file is subject to the MIT License
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/mit-license.php
 * 
 * @category       Medvslav
 * @package        Medvslav_News2
 * @copyright      Copyright (c) 2016
 * @license        http://opensource.org/licenses/mit-license.php MIT License
 */
/**
 * Newscategory list template
 *
 * @category    Medvslav
 * @package     Medvslav_News2
 * @author      Medvslav
 */
?>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<?php $_newscategories = $this->getNewscategories(); ?>
<div class="page-title newscategory-title">
    <h1><?php echo Mage::helper('medvslav_news2')->__('Nescategories') ?></h1>
</div>
<?php if ($_newscategories->getSize() > 0) :?>
    <?php if ($this->_getDisplayMode() == 0) : ?>
        <?php echo $this->getPagerHtml(); ?>
        <div class="newscategory-list-container">
            <?php foreach ($_newscategories as $_newscategory) : ?>
                <div class="newscategory-list-item">
            <a href="<?php echo $_newscategory->getNewscategoryUrl()?>">
                <?php echo $_newscategory->getName();?>
            </a><br />
                </div>
            <?php endforeach;?>
        </div>
        <?php echo $this->getPagerHtml(); ?>
    <?php else : ?>
        <ul id="newscategories-list">
            <?php foreach ($_newscategories as $_newscategory) : ?>
                <?php echo $this->drawNewscategory($_newscategory);?>
            <?php endforeach;?>
        </ul>
        <script type="text/javascript">
            news2Tree('newscategories-list');
        </script>
    <?php endif;?>
<?php else : ?>
    <?php echo Mage::helper('medvslav_news2')->__('There are no nescategories at this moment');?>
<?php endif;?>
