<?php 
/**
 * Medvslav_News2 extension
 * 
 * NOTICE OF LICENSE
 * 
 * This source file is subject to the MIT License
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/mit-license.php
 * 
 * @category       Medvslav
 * @package        Medvslav_News2
 * @copyright      Copyright (c) 2016
 * @license        http://opensource.org/licenses/mit-license.php MIT License
 */
/**
 * Author list template
 *
 * @category    Medvslav
 * @package     Medvslav_News2
 * @author      Medvslav
 */
?>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<?php $_authors = $this->getAuthors(); ?>
<div class="page-title author-title">
    <h1><?php echo Mage::helper('medvslav_news2')->__('Authors') ?></h1>
</div>
<?php if ($_authors->getSize() > 0) :?>
    <?php echo $this->getPagerHtml(); ?>
    <div class="author-list-container">
    <?php foreach ($_authors as $_author) : ?>
        <div class="author-list-item">
            <a href="<?php echo $_author->getAuthorUrl()?>">
                <?php echo $_author->getName();?>
            </a><br />
        </div>
    <?php endforeach;?>
    </div>
    <?php echo $this->getPagerHtml(); ?>
<?php else : ?>
    <?php echo Mage::helper('medvslav_news2')->__('There are no authors at this moment');?>
<?php endif;?>
