<?php
/**
 * Medvslav_News2 extension
 * 
 * NOTICE OF LICENSE
 * 
 * This source file is subject to the MIT License
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/mit-license.php
 * 
 * @category       Medvslav
 * @package        Medvslav_News2
 * @copyright      Copyright (c) 2016
 * @license        http://opensource.org/licenses/mit-license.php MIT License
 */
/**
 * Article list template on product page
 *
 * @category    Medvslav
 * @package     Medvslav_News2
 * @author      Medvslav
 */
?>
<?php $articles = $this->getArticleCollection();?>
<?php if ($articles && $articles->count() > 0) :?>
<div class="box-collateral box-articles box-up-sell">
    <?php foreach ($articles as $_article) : ?>
        <div class="item">
            <a href="<?php echo $_article->getArticleUrl()?>">
                <?php echo $_article->getTitle();?>
            </a><br />
        </div>
    <?php endforeach; ?>
</div>
<?php endif;?>
