<?php
/**
 * Medvslav_News2 extension
 * 
 * NOTICE OF LICENSE
 * 
 * This source file is subject to the MIT License
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/mit-license.php
 * 
 * @category       Medvslav
 * @package        Medvslav_News2
 * @copyright      Copyright (c) 2016
 * @license        http://opensource.org/licenses/mit-license.php MIT License
 */
/**
 * Article product list template
 *
 * @category    Medvslav
 * @package     Medvslav_News2
 * @author      Medvslav
 */
?>
<?php $products = $this->getProductCollection();?>
<?php if ($products->count() > 0) :?>
<h2><?php echo Mage::helper('catalog')->__('Products');?></h2>
<div class="box-collateral box-products box-up-sell">
    <?php foreach ($products as $product) : ?>
        <div class="item">
            <a href="<?php echo $product->getProductUrl()?>">
                <?php echo $product->getName();?><br />
            </a>
        </div>
    <?php endforeach; ?>
</div>
<?php endif;?>
